# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-05 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=250, verbose_name='Event Name')),
                ('about', models.CharField(max_length=250, verbose_name='About Event')),
                ('event_image', models.FileField(blank=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=250, verbose_name='category Name')),
                ('winners', models.CharField(max_length=250, verbose_name='Winners name (, separated)')),
                ('runner_ups', models.CharField(max_length=250, verbose_name='Winners name (, separated)')),
            ],
        ),
        migrations.CreateModel(
            name='LibrarySection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=250, verbose_name='section Name')),
            ],
        ),
        migrations.CreateModel(
            name='LibrarySectionCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=250, verbose_name='category Name')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kolej.LibrarySection')),
            ],
        ),
        migrations.CreateModel(
            name='Organizers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='member Name')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kolej.Event')),
            ],
        ),
        migrations.CreateModel(
            name='SubEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_event_name', models.CharField(max_length=250, verbose_name='Sub Event Name')),
                ('about_sub_event', models.CharField(blank=True, max_length=250, verbose_name='About Event')),
                ('sub_event_image', models.FileField(blank=True, upload_to=b'')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kolej.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prof_name', models.CharField(max_length=250, verbose_name='Professor Name')),
                ('qualification', models.CharField(blank=True, max_length=250, verbose_name='Qualification(such as Phd. )')),
                ('qualification_institute', models.CharField(blank=True, max_length=250, verbose_name='Institution Qualified From (such as IIT Delhi )')),
                ('area_of_interest', models.CharField(max_length=1250, verbose_name='Areas Of Interest (, separated)')),
                ('contact_info', models.CharField(max_length=250, verbose_name='Email id:')),
                ('image_file', models.FileField(blank=True, upload_to=b'')),
            ],
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='sub_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kolej.SubEvent'),
        ),
    ]
